#!/usr/bin/env zsh

local dir="$1"
local lock_icon
local bookmark_icon="%{${c[blue]}${c[dim]}%}%{${c[reset]}%} "

if [[ -z $dir ]]; then
  echo ''
  return 0
fi

if [[ "$dir" == '/' ]]; then
  echo ''
  return 0
fi

if [[ ! -w "$dir" ]]; then
  lock_icon="%{${c[red]}${c[dim]}%}%{${c[reset]}%} "
else
  lock_icon=""
fi

if [[ -e "${ZPM_BOOKMARKS_FILE:-"${XDG_CONFIG_HOME}/zsh/bookmarks"}" ]]; then
  local bookmark_dir=$(pr_cwd_get_bookmark "$dir")

  if [[ -n "${bookmark_dir}" ]] ; then
    echo "${lock_icon}${bookmark_icon}$(hyperlink-file-pr "${bookmark_dir}" "$dir")"
    return 0
  fi
fi

if [[ "$dir" == "$HOME" ]]; then
  echo "${lock_icon}$(hyperlink-file-pr "~" "$dir")"
  return 0
fi

if [[ "${dir}" == "/" ]]; then
  local one_dir="$(pr_cwd_get_one_dir)"

  echo "${lock_icon}$(hyperlink-file-pr "${one_dir}" "$dir")"
  return 0
fi
