#!/usr/bin/env zsh


local rpath="$(print -D ${1})"

declare -a lines; lines=( "${(@f)"$(<${ZPM_BOOKMARKS_FILE:-"${XDG_CONFIG_HOME}/zsh/bookmarks"})"}" )
declare -a grepped; grepped=( ${(M)lines:#${rpath}\|*} )

if [[ ! -z "${grepped}" ]] then
  echo -n "%{${c[cyan]}${c[bold]}%}"
  echo -n ${grepped##*\|}
  echo -n "%{${c[reset]}%}"

  return 0
else
  return 1
fi
