#!/usr/bin/env zsh

function pr_cwd_get_bookmark() {
  local rpath="$(print -D ${1:P})"

  declare -a lines; lines=( "${(@f)"$(<${BOOKMARKS_FILE:-"$HOME/.bookmarks"})"}" )
  declare -a grepped; grepped=( ${(M)lines:#${rpath}\|*} )

  if [[ ! -z "${grepped}" ]] then
    echo -n "%{${c[cyan]}${c_bold}%}"
    echo -n ${grepped##*\|}
    echo -n "%{${c_reset}%}"

    return 0
  else
    return 1
  fi
}
