#!/usr/bin/env zsh

package_str='Unknown name'

if (( $+commands[jq] )); then
  package_str="$(
    cargo metadata --no-deps --format-version 1 --manifest-path="${1}/Cargo.toml" \
      | jq --raw-output "(.packages[0] | .name) + \"%{${c[grey]}%}#%{${c[bright_grey]}%}\" + (.packages[0] | .version)"  2>/dev/null
  )"
fi

echo -n "%{${c[magenta]}${c[bold]}%}${package_str}%{${c[reset]}%}"
